### ISSUE TITLE
Error with append_table

### ISSUE THREAD

**Issue by frankvgompel** [hakonmh/featherstore#1]
Trying to use append_table gives me errors:

When using a polars dataframe and 

`store.append_table('table', df)`

I get the following message:

```
Traceback (most recent call last):
[...] /FeatherStore/venv/lib/python3.10/site-packages/featherstore/_table/_table_utils.py", line 197, in _get_index_as_pd_index
    index = df[index_name]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/polars/internals/frame.py", line 1618, in __getitem__
    return pli.wrap_s(self._df.column(item))
exceptions.NotFoundError: __index_level_0__
```
And when attempting  a pandas data frame I get the message:

```
[...] raise ValueError(
ValueError: New_data.index can't be <= old_data.index[-1] (0 <= 176270)
```

**Comment by hakonmh** [comment]
Featherstore uses sorted indices when storing its data. ``append_table()`` raises an exception when the index values of the appended data is not higher than the last index value of the already stored data (i.e. when appending new data would make the index unsorted). 

In your case it looks like Featherstore uses a default index (but hard to say given the info), which is a rangeindex added if no other index is specified when using `write_table()`.

Normally, Featherstore should automatically continue from the last value (`176270`) when using a default index, but doens't do that in this case. I'll take a look into why. 

Meanwhile, you can fix your error by adding a pandas rangeindex (`pd.RangeIndex(len(df)) + 176271`) as an index or by adding a column named `"__index_level_0__"` and it populating with the same pandas rangeindex values.

**Comment by frankvgompel** [comment]
No, I didn't specify any index with write.table() so it should indeed be a default one. Thanks for looking into it and congrats with your interesting project!

**Comment by hakonmh** [comment]
Thanks! 

Try `pip install git+https://github.com/hakonmh/featherstore.git@append_default_idx_fix` and see if that fixes the issue.

**Comment by frankvgompel** [comment]
Sorry, I am not familiar with that approach. Should that update the append.py and other files? I can't see any differences in the site package in the venv.

```
(venv) frankvangompel@MBP-van-Frank FeatherStore % pip install git+https://github.com/hakonmh/featherstore.git@append_default_idx_fix
Collecting git+https://github.com/hakonmh/featherstore.git@append_default_idx_fix
  Cloning https://github.com/hakonmh/featherstore.git (to revision append_default_idx_fix) to /private/var/folders/hw/xwcqxx2n1jx1mblrnvbxn0rm0000gn/T/pip-req-build-qsvbu_pr
  Running command git clone --filter=blob:none --quiet https://github.com/hakonmh/featherstore.git /private/var/folders/hw/xwcqxx2n1jx1mblrnvbxn0rm0000gn/T/pip-req-build-qsvbu_pr
  Running command git checkout -b append_default_idx_fix --track origin/append_default_idx_fix
  Switched to a new branch 'append_default_idx_fix'
  Branch 'append_default_idx_fix' set up to track remote branch 'append_default_idx_fix' from 'origin'.
  Resolved https://github.com/hakonmh/featherstore.git to commit 10a7ac822aa1778bb7abfea22656d8d59e140447
  Preparing metadata (setup.py) ... done
```
In any case I still get the same error messages with both polars and pandas df.

**Comment by hakonmh** [comment]
The command above is used to install a specific github branch.

You may have to run `pip uninstall featherstore` first, since i haven't updated the version number in `setup.py`, making pip think that the version already installed is the same as the version you want to install.

**Comment by hakonmh** [comment]
Updated the branch version number, so `pip install git+https://github.com/hakonmh/featherstore.git@append_default_idx_fix` should now work without running `pip uninstall` first

**Comment by frankvgompel** [comment]
Great. Seems to work fine now.
